config/routes.rb
PictureThis::Application.routes.draw do
  devise_for :users 

  resources :users do
    resources :favourites
    member do
      get :following, :followers
    end

  end

  get "welcome/index"
  get "/photos/new"
  get "/photos/show"

   
   resources :photos do 
    resources :comments
    put :favourite, on: :member
     
  end
    resources :tags
   root :to => "photos#index"

   resources :profiles
   resources :messages
   resources :conversations

   resources :relationships, only: [:create, :destroy]
   

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
end

app/models/favourite_photo.rb
class FavouritePhoto < ActiveRecord::Base
	belongs_to :photo
	belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :user
  has_many :favourite_photos, dependent: :destroy
  has_many :favourites, through: :favourite_photos, source: :user

	has_many :comments
	
	has_and_belongs_to_many :tags

	has_attached_file :image,
                    styles: { medium: "400x400#", thumb: "200x200#" }
    validates :title, presence: true,
                    length: { minimum: 5, message: "Title must be at least 5 characters" }
    validates :image, attachment_presence: { message: 'Need a photo' }


  def tag_names
    ''
  end

  def tag_names=(tags_string)
    tags_string.split(' ').each do |tag|
    	      new_tag = Tag.find_or_create_by(name: tag)
            new_tag.slug = new_tag.name.gsub('#', '').downcase
            new_tag.save
            self.tags << new_tag
    end
  end
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base

	  include Gravtastic
  	gravtastic

	belongs_to :user
	delegate :followers, :followed_users, :to => :users

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
  	validates :followed_id, presence: true

end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_and_belongs_to_many :photos

	def to_param
		slug
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_one :profile, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :favourite_photos
  has_many :favourites, through: :favourite_photos, source: :photo
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  after_create :build_profile
  acts_as_messageable

  include Gravtastic
  gravtastic
  

  def build_profile
    Profile.create(user: self) # Associations must be defined correctly for this syntax, avoids using ID's directly.
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end

  
  def mailboxer_email(object)
    nil
  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
before_filter :authenticate_user!
	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(params[:photo].permit(:title, :text, :image, :tag_names, :user_id))

		if @photo.save
			flash[:notice] = 'Photo added'
	      	redirect_to photos_path
	  else
	  	render "new"
	  end
	end

	def index
		@photos = Photo.all
	end

	def show
  		@photo = Photo.find(params[:id])
	end

	def edit
  		@photo = Photo.find(params[:id])
	end

	def update
	  	@photo = Photo.find(params[:id])
	 
	  	if @photo.update(params[:photo].permit(:title, :text, :image, :tag_names, :user_id))
	    	flash[:notice] = 'Photo updated'
	    	redirect_to photos_path
	  	else
	    	render 'edit'
	  	end
	end

	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy
		 
		redirect_to photos_path
	end


	def favourite
		@photo = Photo.find(params[:id])

    type = params[:type]
    if type == "favourite"
      current_user.favourites << @photo
      redirect_to :back, notice: "You favourited #{@photo.title}"
      
    elsif type == "unfavourite"
      current_user.favourites.delete(@photo)
      redirect_to :back, notice: "Unfavourited #{@photo.title}"

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end



	private
	def photo_params
	    params.require(:photo).permit(:title, :text, :image, :tag_names)

	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	# def create
	#   @user = User.new(user_params)
	#   if @user.save
	#     redirect_to root_url, :notice => "You have succesfully signed up!"
	#   @profile = Profile.new(params[:profile].permit(:first_name, :second_name, :home_town, :date_of_birth))
	#   if @profile.save
	#     redirect_to edit_profile_path, :notice => "You have succesfully signed up!"
	#   else
	#     render "new"
	#   end
	# end

	def index
			@profile = Profile.all 
	end

	def edit
			@profile = Profile.find(params[:id])
	end

	def update
			@profile = Profile.find(params[:id])
	 
	  	if @profile.update(params[:profile].permit(:username, :first_name, :second_name, :home_town, :gender, :date_of_birth))
	    	flash[:notice] = 'Profile updated'
	    	redirect_to profile_path
	  	else
	    	render 'edit'
	  	end

	end

	def show
			@profile = Profile.find(params[:id])
			@photos = @profile.user.photos
			@user = User.find(params[:id])
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def show
		@tag = Tag.find_by slug: params[:id]
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json

  before_action :current_user,
                only: [:index, :edit, :update, :destroy, :following, :followers]

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end


  private

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
    	gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    	"http://gravatar.com/avatar/#{gravatar_id}.png"
  	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper

	def tag_names(photo)
		tag_links = photo.tags.map do |tag|
                        link_to(tag.name, tag)
                end

                tag_links.join(", ").html_safe
	end
	
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/profiles/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(current_user.profile) do |f| %>

      <p> <%= f.label :username %>
      <%= f.text_field :username %> </p>

      <p> <%= f.label :first_name %>
      <%= f.text_field :first_name %> </p>

      <p> <%= f.label :second_name %>
      <%= f.text_field :second_name %> </p>

      <p> <%= f.label :home_town %>
      <%= f.text_field :home_town %> </p>

      <p> <%= f.label :sex %>
      <p> <%= f.select :gender, [["Male"],["Female"], ["Yes please"], ["Not until marraige"], ["I don't understand"]] %>

      <p> <%= f.label :date_of_birth %>
      <%= f.text_field :date_of_birth %> </p>




      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/profiles/index.html.erb
<% provide(:title, 'All users') %>
<h1>People</h1>
<br>
<div>
<ul class="users">
  <% @profile.each do |profile| %>


      <p><%= image_tag profile.user.gravatar_url %></p>
      <%# link_to profile.name, profile %>
      <p id="user">
  <strong>
  <%= profile.username %>
  <%= link_to profile_path(profile) do %><i class="fa fa-laptop"></i><% end %>
</p></strong>

    
  <% end %>
</ul>
</div>

app/views/profiles/show.html.erb
<div id="wrap">
<div><% if @user != current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <% end %>

  <% @user ||= @profile.user %>
  <% if @user != current_user %>
	  <a>
	  	<%= render "users/follow_form" %>
	  </a>
	<% end %>
</div>
<p><%= image_tag @user.gravatar_url %></p>
<a href="http://gravatar.com/emails">upload photo</a>

<p>  
  <strong>Name:</strong>
  <%= @profile.first_name %>
  <%= @profile.second_name %>
  <a href="/messages/new"><i class="fa fa-pencil-square fa-2x"></i></a>
</p>

<p>
  <strong>Sex:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile.date_of_birth %>
</p>
 

<p>
  <strong>Location:</strong>
  <%= @profile.home_town %>
</p>
<div>


<% @photos.each do |photo| %>
  <div class='col-md-4'>
    <h3><%= photo.title %></h3>
    <%= link_to photo_path(photo) do %>
      <%= image_tag(photo.image.url(:thumb), class: 'uploaded-pic') %>
    <% end %>
  </div>
<% end %>
<div>
  
</div>