config/routes.rb
PictureThis::Application.routes.draw do
  devise_for :users 

  resources :users do
    resources :favourites
    member do
      get :following, :followers
    end

  end

  get "welcome/index"
  get "/photos/new"
  get "/photos/show"

   
   resources :photos do 
    resources :comments
    put :favourite, on: :member
     
  end
    resources :tags
   root :to => "photos#index"

   resources :profiles
   resources :messages
   resources :conversations

   resources :relationships, only: [:create, :destroy]
   

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_mailbox, :get_box #, :get_user
  before_filter :check_current_subject_in_conversation, :only => [:show, :update]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox#.page(params[:page]).per(9)
    elsif @box.eql? "sentbox"
      @conversations = @mailbox.sentbox#.page(params[:page]).per(9)
    else
      @conversations = @mailbox.trash #.page(params[:page]).per(9)
    end

    respond_to do |format|
      format.html { render @conversations if request.xhr? }
    end
  end

  def show
    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    render :action => :show
    @receipts.mark_as_read
  end

  def update
    if params[:untrash].present?
    @conversation.untrash(@user)
    end

    if params[:reply_all].present?
      last_receipt = @mailbox.receipts_for(@conversation).last
      @receipt = @user.reply_to_all(last_receipt, params[:body])
    end

    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    redirect_to :action => :show
    @receipts.mark_as_read

  end

  def destroy


  	@conversation = Conversation.find(params[:id])
	@conversation.destroy
	redirect_to conversations_path

    #@conversation.move_to_trash(@user)

    # respond_to do |format|
    #   format.html {
    #     if params[:location].present? and params[:location] == 'conversation'
    #       puts 'should go here'
    #       redirect_to conversations_path(:box => :trash)

    #     else
    #     	puts 'going here?'
    #       redirect_to conversations_path(:box => @box,:page => params[:page])
    #     end
    #   }
    #   format.js {
    #     if params[:location].present? and params[:location] == 'conversation'
    #       render :js => "window.location = '#{conversations_path(:box => @box,:page => params[:page])}';"
    #     else
    #       render 'conversations/destroy'
    #     end
    #   }
    # end
  end

  private

  def get_mailbox
    @mailbox = current_user.mailbox
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      params[:box] = 'inbox'
    end

    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = Conversation.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@user)
      redirect_to conversations_path(:box => @box)
    return
    end
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= div_for(conversation, :class =>"#{ 'unread ' if conversation.is_unread?(@actor) }") do %>

  <div class="content_left">
    <header>
      <h5>
         <%= link_to conversation.last_sender.profile.first_name, profile_path(conversation.last_sender.profile) %>
      
      

    </header>

  </div>
  <div class="content_right">
<div class="panel panel-default">
  <div class="panel-body">
    <div class="subject">
  
 
       <%= link_to(truncate(conversation.subject, :length => 55), conversation_path(conversation.id,:box => @box,:page => params[:page])) %>
    </div>
   

    <% unless @box.eql?'trash' %>
      <div class="action">
      
      </div>
    <% end %>
     <div class="panel panel-default">
  <div class="panel-body">
    <div class="briefing">
      <%= raw(truncate(strip_tags(conversation.last_message.body), :length => 140)) %>
    </div>
  </div>
<% end %>

<div class="date">
         <%= time_ago_in_words(conversation.updated_at) %> ago
      </div>
 <p><a href="/messages/new"><i class="fa fa-reply fa-2x"></i></a><%= link_to conversation, :method => :delete, :class => 'action', :confirm => 'Are you sure?' do %><i class="fa fa-trash-o fa-2x"></i><% end %></p>
 </div>
  </div>

app/views/conversations/_conversation_full.html.erb
$("#content").html("<%= escape_javascript(render :partial => 'show') %>");



$('.cont_conversation').validate({errorClass: "validation_error"});
<% unless @box.eql?'trash' %>
  $("#body").cleditor({
    width:493,
    controls:  "<%= SocialStream.cleditor_controls %>"     
  });

        var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
        if (message_hash && message_hash.length > 0){
                $.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
        }else{
                $.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});                
        }

<% else %>
        var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
        if (message_hash && message_hash.length > 0){
                $.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
        }else{
                $.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});                
        }
<% end %>

app/views/conversations/_index.html.erb
<div class="conversations">
  <%= render @conversations %>
</div>

app/views/conversations/_show.html.erb
<div class="conversation_full">  
  <%= render :partial => 'conversation_full', :locals =>{:conversation => @conversation} %>
</div>

app/views/conversations/destroy.js.erb
$('#conversation_<%= @conversation.id %>').remove();

app/views/conversations/edit.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/conversations/index.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<section id="conversations">

  <%= render :partial => 'index' %>

  <%= javascript_tag do %>
    $(function() {
      SocialStream.Conversation.index();
    });
  <% end %>

</section>

app/views/conversations/index.js.erb
$("#content").html("<%=escape_javascript(render :partial => 'index') %>");
<%= location(link_to(image_tag("btn/message_" + @box + ".png", :class => "menu_icon")+t('message.' + @box), conversations_path(:box => @box),:remote => true)) %>

$('.pagination a').attr('data-remote', 'true');
          

app/views/conversations/show.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<section id="conversation">
  # render partial: 'toolbar/messages' %>

  <%= render :partial => 'show' %>

  <%= javascript_tag do %>
$('.cont_conversation').validate({errorClass: "validation_error"});
<% unless @box.eql?'trash' %>
  $("#body").cleditor({
    width:493,
    controls:  "<%= SocialStream.cleditor_controls %>"    
  });

                var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
                if (message_hash && message_hash.length > 0){
                        $.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
                }else{
                        $.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});                
                }
<% else %>
                var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
                if (message_hash && message_hash > 0){
                        $.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
                }else{
                        $.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});        
                }
<% end %>
<% end %>
</section>

app/views/conversations/show.js.erb
$("#content").html("<%= escape_javascript(render :partial => 'show') %>");

<%= toolbar :messages %>

$('.cont_conversation').validate({errorClass: "validation_error"});
<% unless @box.eql?'trash' %>
  $("#body").cleditor({
    width:493,
    controls:  "<%= SocialStream.cleditor_controls %>"     
  });

        var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
        if (message_hash && message_hash.length > 0){
                $.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
        }else{
                $.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});                
        }

<% else %>
        var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
        if (message_hash && message_hash.length > 0){
                $.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
        }else{
                $.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});                
        }
<% end %>